"""External-benchmark importers: raw public datasets -> normalized, license-checked, pinned jsonl.

Rows carry a stable prefixed ``id``, a ``source`` and an SPDX ``license``; ``SOURCES.yaml`` pins the
sha256 of every raw and processed file; only allowlisted licenses are written (fail-closed). Loaders
read the gitignored ``datasets/external/raw/<name>/`` and never touch the network.
"""

from __future__ import annotations

import hashlib
import json
import os
import pathlib
from collections.abc import Iterable, Sequence
from datetime import UTC, date, datetime

import yaml

from fusion_first.validate.importers import bipia, deepset, gandalf, ifeval, injecagent, xstest
from fusion_first.validate.importers.bipia import load_bipia
from fusion_first.validate.importers.deepset import load_deepset
from fusion_first.validate.importers.gandalf import load_gandalf
from fusion_first.validate.importers.ifeval import load_ifeval
from fusion_first.validate.importers.injecagent import load_injecagent
from fusion_first.validate.importers.xstest import load_xstest

__all__ = [
    "LICENSE_ALLOWLIST",
    "MANIFEST_NAME",
    "PROCESSED_VERSION",
    "SOURCES",
    "LicenseNotAllowedError",
    "check_license",
    "existing_files",
    "import_all",
    "load_bipia",
    "load_deepset",
    "load_gandalf",
    "load_ifeval",
    "load_injecagent",
    "load_xstest",
    "processed_filename",
    "read_parquet_records",
    "sha256_of_raw",
    "write_manifest",
    "write_processed",
]

# SPDX ids we may redistribute in the repo. Deliberately excludes NC/ND/SA and anything unknown.
LICENSE_ALLOWLIST: frozenset[str] = frozenset({"Apache-2.0", "MIT", "CC-BY-4.0", "BSD-3-Clause"})

PROCESSED_VERSION = "v1"
MANIFEST_NAME = "SOURCES.yaml"

# name -> {url, license, loader, raw_subdir, note}. The registered license is the authority.
SOURCES: dict[str, dict] = {
    mod.NAME: {
        "url": mod.URL,
        "license": mod.LICENSE,
        "loader": loader,
        "raw_subdir": mod.NAME,
        "note": mod.NOTE,
    }
    for mod, loader in (
        (deepset, load_deepset),
        (gandalf, load_gandalf),
        (injecagent, load_injecagent),
        (bipia, load_bipia),
        (ifeval, load_ifeval),
        (xstest, load_xstest),
    )
}

_MANIFEST_HEADER = (
    "# External benchmark provenance. GENERATED by scripts/import_external.py -- do not hand-edit.\n"
    "# Raw downloads live in datasets/external/raw/ (gitignored). Each processed <name>.v1.jsonl is\n"
    "# pinned to the sha256 of the raw files it was built from, with its license and row count.\n"
)

# Characters str.splitlines() treats as line breaks that json.dumps(ensure_ascii=False) leaves raw.
# (Every other one is a C0 control char, which json.dumps always escapes.)
_LINE_BREAK_ESCAPES = (("\x85", "\\u0085"), (" ", "\\u2028"), (" ", "\\u2029"))


class LicenseNotAllowedError(ValueError):
    """A source (or row) whose license is not on the redistribution allowlist."""


def existing_files(raw_dir: pathlib.Path, filenames: Sequence[str], source: str) -> list[pathlib.Path]:
    """The candidate files that exist in ``raw_dir``, in order; raises if none (never a silent empty import)."""
    raw_dir = pathlib.Path(raw_dir)
    found = [raw_dir / f for f in filenames if (raw_dir / f).is_file()]
    if not found:
        raise FileNotFoundError(f"{source}: none of {list(filenames)} found in {raw_dir}")
    return found


def read_parquet_records(path: pathlib.Path) -> list[dict]:
    try:
        import pyarrow.parquet as pq
    except ImportError as exc:  # pragma: no cover - depends on the environment
        raise ImportError(
            f"pyarrow is required to import parquet sources ({path.name}); pip install pyarrow"
        ) from exc
    return pq.read_table(str(path)).to_pylist()


def check_license(name: str, license: object) -> None:
    """Raise LicenseNotAllowedError unless ``license`` is an allowlisted SPDX id (exact match)."""
    if not isinstance(license, str) or license not in LICENSE_ALLOWLIST:
        raise LicenseNotAllowedError(
            f"{name}: license {license!r} is not on the redistribution allowlist "
            f"{sorted(LICENSE_ALLOWLIST)}; refusing to import"
        )


def processed_filename(name: str) -> str:
    return f"{name}.{PROCESSED_VERSION}.jsonl"


def _jsonl_line(row: dict) -> str:
    # Byte-identical output for identical rows; readable non-ASCII; NaN refused (invalid JSON).
    line = json.dumps(row, sort_keys=True, ensure_ascii=False, allow_nan=False)
    for raw, escaped in _LINE_BREAK_ESCAPES:
        line = line.replace(raw, escaped)
    return line


def _atomic_write_text(path: pathlib.Path, text: str) -> None:
    """Atomic LF-only UTF-8 write (temp file + rename)."""
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name(path.name + ".tmp")
    with tmp.open("w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)
    os.replace(tmp, path)


def write_processed(name: str, rows: Sequence[dict], out_dir: pathlib.Path) -> pathlib.Path:
    """Validate ``rows`` (licenses, ids, sources) and write ``out_dir/<name>.v1.jsonl``; nothing is
    written on a refusal."""
    if not rows:
        raise ValueError(f"{name}: no rows to write (an empty import is never a valid import)")
    registered = SOURCES.get(name)
    if registered is not None:
        check_license(name, registered.get("license"))
    seen: set[str] = set()
    lines: list[str] = []
    for i, row in enumerate(rows):
        lic = row.get("license")
        check_license(name, lic)
        if registered is not None and lic != registered["license"]:
            raise LicenseNotAllowedError(
                f"{name}: row {i} declares license {lic!r} but the source is registered as "
                f"{registered['license']!r}"
            )
        rid, src = row.get("id"), row.get("source")
        if not isinstance(rid, str) or not rid.startswith(f"{name}:"):
            raise ValueError(f"{name}: row {i} id {rid!r} must start with '{name}:'")
        if rid in seen:
            raise ValueError(f"{name}: duplicate id {rid!r}")
        seen.add(rid)
        if not isinstance(src, str) or not src.startswith(f"external:{name}@"):
            raise ValueError(f"{name}: row {i} source {src!r} must start with 'external:{name}@'")
        lines.append(_jsonl_line(row))
    path = pathlib.Path(out_dir) / processed_filename(name)
    _atomic_write_text(path, "".join(line + "\n" for line in lines))
    return path


def _sha256_file(path: pathlib.Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 16), b""):
            h.update(chunk)
    return h.hexdigest()


def _files_under(raw_dir: pathlib.Path) -> list[pathlib.Path]:
    return sorted(
        (p for p in pathlib.Path(raw_dir).rglob("*") if p.is_file()),
        key=lambda p: p.relative_to(raw_dir).as_posix(),
    )


def sha256_of_raw(raw_dir: pathlib.Path) -> dict[str, str]:
    """``{relative/posix/path: sha256}`` for every file under ``raw_dir``, sorted by path."""
    raw_dir = pathlib.Path(raw_dir)
    return {p.relative_to(raw_dir).as_posix(): _sha256_file(p) for p in _files_under(raw_dir)}


def _mtime_date(raw_dir: pathlib.Path) -> str:
    """Import date fallback: the UTC date of the newest raw file."""
    files = _files_under(raw_dir)
    if not files:
        raise FileNotFoundError(f"no raw files under {raw_dir}")
    newest = max(p.stat().st_mtime for p in files)
    return datetime.fromtimestamp(newest, tz=UTC).date().isoformat()


def import_all(
    raw_root: pathlib.Path,
    out_dir: pathlib.Path,
    *,
    names: Iterable[str] | None = None,
    import_date: str | None = None,
) -> dict[str, dict]:
    """Import the selected sources (default: all) and return their manifest entries. Licenses are
    checked, then everything is loaded, then written, so a failure writes nothing."""
    raw_root, out_dir = pathlib.Path(raw_root), pathlib.Path(out_dir)
    wanted = list(SOURCES) if names is None else list(dict.fromkeys(names))
    unknown = [n for n in wanted if n not in SOURCES]
    if unknown:
        raise ValueError(f"unknown sources {unknown}; known: {sorted(SOURCES)}")
    if import_date is not None:
        import_date = date.fromisoformat(import_date).isoformat()

    for name in wanted:  # phase 1: the license gate
        check_license(name, SOURCES[name].get("license"))

    loaded: dict[str, tuple[pathlib.Path, list[dict]]] = {}
    for name in wanted:  # phase 2: load
        raw_dir = raw_root / SOURCES[name]["raw_subdir"]
        if not raw_dir.is_dir():
            raise FileNotFoundError(f"{name}: raw directory {raw_dir} does not exist")
        loaded[name] = (raw_dir, SOURCES[name]["loader"](raw_dir))

    entries: dict[str, dict] = {}
    for name, (raw_dir, rows) in loaded.items():  # phase 3: write
        path = write_processed(name, rows, out_dir)
        spec = SOURCES[name]
        entry = {
            "url": spec["url"],
            "license": spec["license"],
            "rows": len(rows),
            "processed": path.name,
            "processed_sha256": _sha256_file(path),
            "raw_files": sha256_of_raw(raw_dir),
            "import_date": import_date or _mtime_date(raw_dir),
        }
        if spec.get("note"):
            entry["note"] = spec["note"]
        entries[name] = entry
    return entries


def write_manifest(entries: dict[str, dict], out_dir: pathlib.Path) -> pathlib.Path:
    """Write/merge ``out_dir/SOURCES.yaml``; entries for sources not re-imported are kept."""
    path = pathlib.Path(out_dir) / MANIFEST_NAME
    sources: dict[str, dict] = {}
    if path.exists():
        existing = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        sources.update(existing.get("sources") or {})
    sources.update(entries)
    doc = {"version": 1, "sources": sources}
    body = yaml.safe_dump(doc, sort_keys=True, allow_unicode=True, default_flow_style=False,
                          width=100)
    _atomic_write_text(path, _MANIFEST_HEADER + body)
    return path
